testapp/testapp/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic.detail import DetailView

from music.models import Band
from music.views import BandExtendedUpdateView

admin.autodiscover()

urlpatterns = patterns('',
	url(r'^read/(?P<pk>[\d]+)/$', DetailView.as_view(model=Band), name="detail"),
    url(r'^extended-update/(?P<pk>[\d]+)/$', BandExtendedUpdateView.as_view(), name="extended-update"),
    url(r'^admin/', include(admin.site.urls)),
)

testapp/music/models.py
# -*- coding: utf8 -*-
from django.core.urlresolvers import reverse
from django.db import models


class Artist(models.Model):
    name = models.CharField(max_length=255)

    def __unicode__(self):
        return self.name


class Role(models.Model):
    label = models.CharField(max_length=255)

    def __unicode__(self):
        return self.label


class Band(models.Model):
    name = models.CharField("Band name", max_length=255)
    members = models.ManyToManyField(Artist, through='Membership')

    def get_absolute_url(self):
        return reverse('detail', args=[str(self.id)])

    def __unicode__(self):
        return self.name


class Membership(models.Model):
    artist = models.ForeignKey(Artist)
    band = models.ForeignKey(Band)
    roles = models.ManyToManyField(Role)


class Record(models.Model):
    title = models.CharField("Record title", max_length=255)
    band = models.ForeignKey(Band)

    def __unicode__(self):
        return self.title


class Track(models.Model):
    title = models.CharField("Track title", max_length=255)
    record = models.ForeignKey(Record)
    contributions = models.ManyToManyField(Artist, through="ArtistContribution")

    def __unicode__(self):
        return self.title


class ArtistContribution(models.Model):
    track = models.ForeignKey(Track)
    artist = models.ForeignKey(Artist)
    roles = models.ManyToManyField(Role)
    
    def __unicode__(self):
        try:
            return "%s-%s-%s" % (self.track, self.instrument, self.artist)
        except:
            return None


class Concert(models.Model):
    band = models.ForeignKey(Band)
    date_time = models.DateTimeField()
    place = models.CharField(max_length=255)
    price = models.IntegerField()
    playlist = models.ManyToManyField(Track, through="TrackPlaylist")


class TrackPlaylist(models.Model):
    track = models.ForeignKey(Track)
    concert = models.ForeignKey(Concert)
    order = models.IntegerField()

testapp/nestedformsets/models.py
from django.db import models

# Create your models here.

testapp/music/forms.py
from django.forms import ModelForm
from .models import Band


class BandForm(ModelForm):
	class Meta:
		model = Band
		exclude = ('members', )

testapp/music/views.py
# -*- coding: utf8 -*-

from django.views.generic import UpdateView
from django.http import HttpResponseRedirect 

from nestedformsets import *
from .models import *
from .forms import BandForm

def flatten(*args):
    for x in args:
        if hasattr(x, '__iter__'):
            for y in flatten(*x):
                yield y
        else:
            yield x


class BandExtendedUpdateView(UpdateView):
    model = Band
    template_name = "music/update.html"

    form_class = BandForm
    
    def form_valid(self, form):        
        context = self.get_context_data()
        if all(list(flatten([formset.is_valid() for formset in context['formsets']]))):
            for formset in context['formsets']:
                formset.save()
                self.object = form.save()

        return HttpResponseRedirect(self.get_success_url())

    def get_context_data(self, **kwargs):
        context = super(BandExtendedUpdateView, self).get_context_data(**kwargs)
        context['formsets'] = [f(**self.get_form_kwargs()) for f in extended_nested_formset_factory(self.model)]
        return context

testapp/nestedformsets/views.py
# Create your views here.

testapp/testapp/templates/music/band_detail.html
<!doctype html>
<html lang="en">

<head>
</head>

<body>
	<h1>{{ object }} (<a href="{% url 'extended-update' object.id %}">edit</a>)</h1>

	<h2>Members</h2>
	<ul>
		{% for m in object.membership_set.all %}
		<li>{{ m.artist }} ({{ m.roles.all|join:", "}})</li>
		{% endfor %}
	</ul>

	<h2>Albums</h2>
	<ul>
		{% for record in band.record_set.all %}
		{{ record.title }}
		<ul>
			{% for track in record.track_set.all %}
			<li>{{ track }}
				<ul>
				{% for artist_contribution in track.artistcontribution_set.all %}
					<li>{{ artist_contribution.artist }} ({{ artist_contribution.roles.all|join:", " }})</li>
				{% endfor %}
				</ul>
			</li>
			{% endfor %}
		</ul>
		{% endfor %}
	</ul>

	<h2>Gigs</h2>

	<ul>
		{% for concert in band.concert_set.all %}
			<li>{{ concert.date_time }} - {{ concert.place }} - {{ concert.price }}€
				<ul>
					{% for track in concert.trackplaylist_set.all %}
						<li>{{ track.track }}</li>
					{% endfor %}
				</ul>
			</li>
		{% endfor %}
	</ul>


</body>


</html>

testapp/testapp/templates/music/form-update-empty.html
<blockquote>
{{ formset.management_form }}

{{ formset.empty_form.as_table }}

    {% for formset in formset.empty_form.nested %}
        <blockquote>
        {% with "music/form-update-empty.html" as filename %}
        {% include filename with formset=formset only  %}
        {% endwith %}
        </blockquote>
    {% endfor %}
</blockquote>

testapp/testapp/templates/music/form-update.html
{% load class_tag %}

<div id="formset-{{ formset.prefix }}" data-formset-prefix="{{ formset.prefix }}">
{{ formset.management_form }}

<header><b>{{ formset|get_class }}</b></header>

{% for form in formset %}

    <blockquote>
    {{ form.as_table }}
    <br />
    {% if form.nested %}
    	{% for formset in form.nested %}
        <blockquote>
    	{% with "music/form-update.html" as filename %}
    	{% include filename with formset=formset only  %}
    	{% endwith %}
        </blockquote>
    	{% endfor %}
    {% endif %}
    </blockquote>

{% endfor %}

{% comment %}

<input type="button" value="Add {{ formset|get_class }}" id="formset-{{ formset.prefix }}-add_more">
<div id="formset-{{ formset.prefix }}-empty_form" style="display:none">
        <blockquote>
        {{ formset.empty_form.as_table }}
        {% if formset.empty_form.nested %}
        {% for formset in formset.empty_form.nested %}
        <blockquote>
            {% with "music/form-update-empty.html" as filename %}
            {% include filename with formset=formset only  %}
            {% endwith %}
        </blockquote>
        {% endfor %}
        {% endif %}
        </blockquote>
</div>

<script>
    $('#formset-{{ formset.prefix }}-add_more').click(function() {
        var form_idx = $('#id_{{ formset.prefix }}-TOTAL_FORMS').val();
        $('#formset-{{ formset.prefix }}-add_more').before($('#formset-{{ formset.prefix }}-empty_form').html().replace(/__prefix__/g, form_idx));
        $('#id_{{ formset.prefix }}-TOTAL_FORMS').val(parseInt(form_idx) + 1);
    });
</script>

{% endcomment %}

</div>

testapp/testapp/templates/music/update.html
{% load class_tag %}

<!doctype html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<script src="{{ STATIC_URL }}js/jquery.js"></script>
	<style type="text/css">
		body {
			font-family: Arial;
		}
		blockquote {
			margin-left:20px;
			border:0px solid white;
			border-bottom: 3px solid #ddd;
			padding:4px;
			background-color: rgba(213, 203, 200, 0.2);
		}
	</style>
</head>
<body>
<h1>Edit band: {{ object }}</h1>

<form action="." method="POST">

	{% csrf_token %}

	<blockquote>
	{{ form }}
	</blockquote>

	{% for formset in formsets %}
	<blockquote> 
	{% include "music/form-update.html" with formset=formset only  %}
	</blockquote>
	{% endfor %}

	<input type="submit" value="Save" />

</body>
</head>